### ISSUE TITLE
[Feature request] Organize Favorites

### ISSUE THREAD

**Issue by dhammel** [CoinTrend/CoinTrend#11]
Hello,

Can you implement a way of organizing favorites? Maybe by dragging them up/down list, as well as an option to organize alphabetically?

Small note: The word Favorites is spelt incorrectly both on the bottom navigation and top left when in favorites. Should be spelt: Favorites

**Comment by davidepanidev** [comment]
Hi @dhammel!

Thanks for reaching out. The reordering feature you suggested is now available from version 1.2, hope you like it. We will also consider the alternative in the next udates.
