### ISSUE TITLE
AboutScreen

### ISSUE THREAD

**Issue by davidepanidev** [CoinTrend/CoinTrend#12]
**Is your feature request related to a problem? Please describe.**
A screen where put links to GitHub source code, GitHub issues, contacts (email), and link to Bitcoin donations.

**Describe the solution you'd like**
A Jetpack Compose Screen (AboutScreen) like the CoinDetailScreen. I'll describe below the items from top to bottom:

- At the top of the Screen there is the toolbar with back arrow like in CoinDetailScreen;
- Below the toolbar a Lazy Column which contains all the following items;
- CoinTrend icon centered and below that the "CoinTrend" name in bold style, like at the top of the README (https://github.com/CoinTrend/CoinTrend#readme);
- Below that there are some sections in the same style of the "MarketData" section in the CoinDetailScreen; so some sections with a title and below it a list of one or more items with a background with rounded corners:
- Section with title "Source Code" and the following item: "GitHub Repository" (https://github.com/CoinTrend/CoinTrend)
- Section with title "Contacts" and the following items: "Email" (cointrend.info@gmail.com) and "GitHub Issues" (https://github.com/CoinTrend/CoinTrend/issues)
- Section with title "Support" and the following items: "Donate Bitcoin" (https://github.com/CoinTrend/CoinTrend#bitcoin), "Rate on Google Play" 

Each item inside a section can be a simple text, but it would be better with an icon placed on the left for each of them (like the crypto Cards that show the crypto icon).

**Additional context**
The Screen is very simple so I see no need to create a corresponding ViewModel.  The navigation to this Screen will be placed in the "Settings" tab that will be added in the following release.

**Comment by ZineeEddine** [comment]
Hi @davidepanidev, I could work on it with @beastboym, we will show you a version as soon as possible
