### ISSUE TITLE
Ability to set desired period of price change on favorites tab.

### ISSUE THREAD

**Issue by DMantis** [CoinTrend/CoinTrend#15]
**Is your feature request related to a problem? Please describe.**
I'm interested in a 24h price percentage change for all saved currencies when I open the favorites tab. Would be nice to have an option to set default period of change to display. Probably a bit tricky, because it makes sense to add settings page first. 

**Describe the solution you'd like**
Implement basic settings page and add a dropdown with default period to display for favorites tab: 1h, 24h, week, month, year.

**Describe alternatives you've considered**
Dropdown or some picker on favorites page (though I think this approach would clutter the interface).

**Will you support the developers through a donation (https://github.com/CoinTrend#support) if/when the feature is implemented?**
- Yes, I can donate 50 USD Bitcoin equivalent for this one.

**Comment by davidepanidev** [comment]
Hi @DMantis,

thanks for reaching out!

We found your suggestion interesting and we will work on it. The idea is to add a Settings page where selecting the default time range. 

The available time ranges will be 24H, 1W, 1M and 1Y and the settings will be applied to all pages so also to the Market one.

Unfortunately, CoinGecko does not provide sparkline data (the smaller chart that you see on each coin in the list) for 1M and 1Y, so for those two settings the chart will not be displayed in the list view.

What do you think about it? Does this meet your requests?

**Comment by DMantis** [comment]
Sure, thanks! I don't think that small chart is anyhow informative for huge ranges anyway.

In fact, on currencies lists page percent are more important part. At least for me.

**Comment by davidepanidev** [comment]
Hi @DMantis,

the feature you requested is now available in the latest release! Please, let us know if everything works as you expected. Thanks in advance

**Comment by DMantis** [comment]
I have troubles installing the current version from F-Droid, could you
check the build on it? Other apps from it update just fine.

**Comment by davidepanidev** [comment]
Hi @DMantis, 

we are sorry that you are having troubles. We checked it today and updating from version 1.2.1 to 1.3.1 went smooth in all cases. 

Have you installed the previous version from Google Play? In that case you cannot update it from F-Droid. If not, could you please provide more information about your setting?

**Comment by DMantis** [comment]
I found another app with the same problem, most probably not connected to CoinTrend, I'll raise the issue with f-droid.

Version from Google Play installs well and the feature request works, thanks!

I'll send the promised donation to XMR address from the repo, btc fees are a bit too high these days.

**Comment by davidepanidev** [comment]
Thanks for contibuting @DMantis. If you have any other suggestions, please reach out again.
