### ISSUE TITLE
Error while updating the prices

### ISSUE THREAD

**Issue by MattRGX** [CoinTrend/CoinTrend#18]
**Describe the bug**
When pulling down to refresh the prices of the coins, i get an error popup down on the screen saying "There has been an error while retrieving data. Please try again later"

**To Reproduce**
1. open the app
2. Try to refresh the prices by pulling down 
3. Error is displaying

**Expected behavior**
Pulling down and then the prices are updated.

**Screenshots**
![image](https://github.com/CoinTrend/CoinTrend/assets/58740578/286a8a3a-6ccf-4002-9868-12742b0f29fd)

**Smartphone (please complete the following information):**
 - Device : Pixel 7
 - OS : Android 13
 - App Version : 1.2.0

**Comment by danumbaman** [comment]
Having the same issue since 6/11/23. Seems coingecko is where they scrap the number sets? I havnt checked cointop but will later...

**Comment by d4f5409d** [comment]
It occurs here too

**Comment by davidepanidev** [comment]
Hi @MattRGX, thanks for reporting the issue. I just published the fix and I released a new App version on the stores. It is already available on Google Play while on F-Droid it usually takes 2 to 3 days. Thanks again for your support and let me know if everything is fine now.

**Comment by MattRGX** [comment]
Thanks, it is fixed now.

You can close the issue :)
