### ISSUE TITLE
permission_ add donate on fdroid app?

### ISSUE THREAD

**Issue by ghost** [CoinTrend/CoinTrend#19]
@davidepanidev 
* is it **ok to add** support link as donate given on https://github.com/CoinTrend/CoinTrend#support
* donate link in [app fdroid metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.cointrend.yml) will create a link on fdroid client in additional to your bitcoin address link

**Comment by davidepanidev** [comment]
Hi @jindam-vani, the donate link has now been added to the metadata and should be visible in the fdroid client. Please let me know if everything is as you expected. 

Thank you so much for your suggestion by the way.
