### ISSUE TITLE
Favourites sort by, reorganize the order of the favourites

### ISSUE THREAD

**Issue by rizajur** [CoinTrend/CoinTrend#6]
**Is your feature request related to a problem? Please describe.**
Favourites sort by, reorganize the order of the favorites missing. So the order is the order you added them and cant adjust it

**Describe the solution you'd like**
Make the order changeable when holding one object (coin) for a while make is possible to move it up / down in the list

**Describe alternatives you've considered**
Sort by (add option for average portfolio token amount or % share ) or sort by performance etc

**Additional context**
Your GitHub repo is missing a XMR address to support your work. Thanks

@davidepanidev in case you just want to push this project and show us you improve the app (source upstream given) i can talk to some people in order to boost the playstore version

**Comment by d4f5409d** [comment]
This has been implemented. I suggest you to close the issue as completed.

**Comment by davidepanidev** [comment]
Hi @rizajur!

Thanks for reaching out. The reordering feature you suggested has now been implemented, hope you like it. We will also consider the alternatives in the next udates.

Unfortunately our team does not currently support XMR donations but we added a Bitcoin address to the Support section of the README https://github.com/CoinTrend#bitcoin.

**Comment by d4f5409d** [comment]
> Hi @rizajur!
> 
> Thanks for reaching out. The reordering feature you suggested has now been implemented, hope you like it. We will also consider the alternatives in the next udates.
> 
> Unfortunately our team does not currently support XMR donations but we added a Bitcoin address to the Support section of the README https://github.com/CoinTrend#bitcoin.

For your interest, you can donate BTC using XMR with the Monerujo wallet on Android. It's pretty useful...

**Comment by rizajur** [comment]
using XMR is simple private and fee superior but do as you wish. i dont like taint from btc where i have no clue where it came from.

**Comment by davidepanidev** [comment]
@rizajur  to meet the requests of the most demanding of you we also added a Monero address https://github.com/CoinTrend#monero to the Support section. Hope it helps!

**Comment by rizajur** [comment]
@davidepanidev for more donations i suggest making an about page with clickable coin buttons and notification that the donation address has been copied into the clipboard, in case people you mobile wallet like caket wallet, unstoppable wallet etc.

**Comment by rizajur** [comment]
@davidepanidev  the xmr address is just on the https://github.com/CoinTrend not the https://github.com/CoinTrend/CoinTrend/README.md visible, please fix that. Thanks.

**Comment by davidepanidev** [comment]
> @davidepanidev the xmr address is just on the https://github.com/CoinTrend not the https://github.com/CoinTrend/CoinTrend/README.md visible, please fix that. Thanks.

Fixed, thanks.
